#!/usr/bin/python3
import argparse
from run_git import git
from grep import grep

parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('--debug', action="store_true")
args = parser.parse_args()

print ("ver -- Versioning Easily Remembered")

out, good = git("reset", show=False, debug=args.debug)
if out.find("Unstaged changes after reset") == 0:
    print ("The following files have unsaved changes:")
    lines = out.split("\n")
    for line in lines:
        if line[0:1] == "M":
            print ("  "+line[2:])
    if input("Go ahead and overwrite these files?").lower()[:1] != "y":
        print ("update incomplete")
        exit(); 0/0

out, good = git("reset --hard", show=False, debug=args.debug)

out, good = git("pull", show=True, debug=args.debug)

out, good = git("submodule update", show=True, debug=args.debug)
