#!/usr/bin/python3
import argparse
from utils import git

parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('--debug', action="store_true")
args = parser.parse_args()

print ("ver -- Versioning Easily Remembered")

out, good = git("status", debug=args.debug)
ret = ""
untracked = []
for r in out.split("\n"):
    if r.find("\tmodified:") == 0:
        ret += r.strip() + "\n"
    elif r.find("\tdeleted:") == 0:
        ret += r.strip() + "\n"
    elif r.find("\tnew file:") == 0:
        ret += r.strip() + "\n"
    elif r.find("\trenamed:") == 0:
        ret += r.strip() + "\n"
    elif r.find("\t") == 0:
        untracked.append(r.strip())
print (ret, end="")
print("%d untracked item%s" % (len(untracked), "s:" if len(untracked)>1 else ":" if len(untracked)==1 else "s"), " ", ", ".join(untracked))
