#!/usr/bin/python3
from run_git import git
from grep import grep

print ("ver -- Versioning Easily Remembered")

out, good = git("status -u no")
print(out)

out, good = git("submodule status --recursive")
print(out)

out, good = git("diff")
out = grep("Subproject commit", out)
print(out)

