#!/usr/bin/python3
import os, sys, argparse
from ver_utils import *

parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('--local', action="store_true")
parser.add_argument('--debug', action="store_true")
args = parser.parse_args()

print ("ver -- Versioning Easily Remembered")

def save(local=False, debug=False, root=True):
    subs = get_subs()
    for sub in subs:
        print ("Processing", sub[0])
        path = os.path.abspath(".")
        os.chdir(sub[0])
        save(local=local, debug=debug, root=False)
        os.chdir(path)
    if root:
        print("Processing root project in", os.path.abspath("."))
    if not local:
        git("fetch", show=debug, debug=debug)
        git("merge --no-edit FETCH_HEAD", show=True, debug=debug)
    git("add .", show=debug, debug=debug)
    git(["commit", "-m", '"ver commit"'], show=debug, debug=debug)
    if not local:
        git("push", show=True, debug=debug)

chdir_root()
save(local=args.local, debug=args.debug)
