print ("I've got a lot to say")
print ("So get up & getaway")
s = input('Hit me one time:')
print(s)
print ("Ipsum lorem")
print ("Ipsum lorem")
print ("Ipsum lorem")
s = input('Hit me two time:')
print(s)
