#!/bin/bash
rm -fr rootbare rooty myroot sub1bare

mkdir rootbare sub1bare rooty

cd rootbare
git init --bare

cd ../sub1bare
git init --bare

cd ../rooty
git init
echo "This represents the root ver project. Please only have one in the path!" > .ver_root
git remote add origin ~/ver/_tests/rootbare

mkdir sub1
cd sub1
git init
git remote add origin ~/ver/_tests/sub1bare
echo "rooty/sub1" > rooty_file1
git add rooty_file1
git commit -am "rooty/rooty_file1 commit 1 (sub1)"
git push --set-upstream origin master

cd ../
git submodule add ~/ver/_tests/rooty/sub1
git submodule update --init
git commit -am "rooty/rooty_file1 commit 1 (rooty)"
git push --set-upstream origin master
