import sys, random
print ("I've got a lot to say")
print ("So get up & getaway %s" % random.randint(0, 10))
s = input('Hit me one time:\n')
print(s)
print ("Ipsum lorem")
print ("Ipsum lorem")
print ("Ipsum lorem")
s = input('Hit me %s time:' % random.randint(0, 10))
print(s)
print ("Tree falls in 4 forests")
